apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: cnn
  name: cnn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cnn
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: cnn
    spec:
      containers:
        - image: brijesh944/emotion_cnn:latest
          name: cnn
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
